### PR TITLE
i27 updates to old badges

### PR DESCRIPTION
**Pull request by Matt-Fitzpatrick**
In this pull request:

* Wincott's Ally and Hollows exploration badge icon and order changes
* Portal Parter and Entrusted with the Secret order changes
* Burgermeisterin alternate text for females
* Day Trader, Monitor Duty, and Rapid Response Member text changes

Todo:

* i27 new defeat badges
* i27 new story arc badges
* i27 new On the Shoulders of Giants and Behind Enemy Lines badges
* i27 new Loyal Customer icon
* Passport and Power Liberator category changes
* Visionary defeats change
* Unabashed availability in instanced MSR

### CODE REVIEW

**Comment by n15g** [comment]
Awesome, thanks for these!

**Comment by AboveTheChemist** [comment]
I am going to edit the On the Shoulders of Giants badge so you can mark that off the to do list. I am also going to be doing some non-i27 related edits this morning. If I have time later today I may start tackling some of the other new i27 badges but I am not 100% sure yet if I will be able to get to them. If I have time, I will comment here again to let you know.

**Comment by AboveTheChemist** [comment]
I've added the missing data for the i27 defeat badges. I'm going to work on the i27 story arc badges shortly.

**Comment by AboveTheChemist** [comment]
I submitted one last pull request along with some files I PM'd to KeyboardKitsune directly that should take care of the last 3 bullets on the to-do list.

**Pull request merged**
